name: cure_team_1
description: A Flutter Clean Architecture project with BLoC (Cubit)

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  date_picker_timeline: ^1.2.7
  device_preview: ^1.2.0
  dotted_border: ^3.1.0
  easy_date_timeline: ^2.0.9
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_map: ^8.2.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^17.0.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  intl_phone_number_input: ^0.7.5
  mobkit_dashed_border: ^0.0.8
  permission_handler: ^11.2.0
  pinput: ^6.0.1
  scrollable_clean_calendar: ^1.5.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0+2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:

  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
  - family: georgia
    fonts:
      - asset: assets/fonts/georgia.ttf
        weight: 400
  - family: PlusJakartaSans
    fonts:
      - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        weight: 400
  - family: Inter_28pt
    fonts:
      - asset: assets/fonts/Inter_28pt-Regular.ttf
        weight: 400
      - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Inter_28pt-Medium.ttf
        weight: 500

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
  field_prefix: resource
  ignore_comments: true
